run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable:
    - duple
    - err check
    - laparoscopy
    - ginkgo linter
    - icons
    - go cyclo
    - simple
    - govt
    - assignees
    - lll
    - misspell
    - nakedest
    - preallocate
    - revive
    - static-check
    - unconvert
    - param
    - unused

version: "2"