# This rule is not used by the project glassflow-etl-k8s-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to etl.glassflow.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: glassflow-etl-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: pipeline-viewer-role
rules:
- apiGroups:
  - etl.glassflow.io
  resources:
  - pipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - etl.glassflow.io
  resources:
  - pipelines/status
  verbs:
  - get
