# This rule is not used by the project glassflow-etl-k8s-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over etl.glassflow.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: glassflow-etl-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: pipeline-admin-role
rules:
- apiGroups:
  - etl.glassflow.io
  resources:
  - pipelines
  verbs:
  - '*'
- apiGroups:
  - etl.glassflow.io
  resources:
  - pipelines/status
  verbs:
  - get
