//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeduplicationConfig) DeepCopyInto(out *DeduplicationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeduplicationConfig.
func (in *DeduplicationConfig) DeepCopy() *DeduplicationConfig {
	if in == nil {
		return nil
	}
	out := new(DeduplicationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestorOperatorConfig) DeepCopyInto(out *IngestorOperatorConfig) {
	*out = *in
	in.KafkaConnectionParams.DeepCopyInto(&out.KafkaConnectionParams)
	if in.KafkaTopics != nil {
		in, out := &in.KafkaTopics, &out.KafkaTopics
		*out = make([]KafkaTopicsConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestorOperatorConfig.
func (in *IngestorOperatorConfig) DeepCopy() *IngestorOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(IngestorOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JoinOperatorConfig) DeepCopyInto(out *JoinOperatorConfig) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]JoinSourceConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JoinOperatorConfig.
func (in *JoinOperatorConfig) DeepCopy() *JoinOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(JoinOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JoinSourceConfig) DeepCopyInto(out *JoinSourceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JoinSourceConfig.
func (in *JoinSourceConfig) DeepCopy() *JoinSourceConfig {
	if in == nil {
		return nil
	}
	out := new(JoinSourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaConnectionParamsConfig) DeepCopyInto(out *KafkaConnectionParamsConfig) {
	*out = *in
	if in.Brokers != nil {
		in, out := &in.Brokers, &out.Brokers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaConnectionParamsConfig.
func (in *KafkaConnectionParamsConfig) DeepCopy() *KafkaConnectionParamsConfig {
	if in == nil {
		return nil
	}
	out := new(KafkaConnectionParamsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaTopicsConfig) DeepCopyInto(out *KafkaTopicsConfig) {
	*out = *in
	out.Deduplication = in.Deduplication
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaTopicsConfig.
func (in *KafkaTopicsConfig) DeepCopy() *KafkaTopicsConfig {
	if in == nil {
		return nil
	}
	out := new(KafkaTopicsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapperConfig) DeepCopyInto(out *MapperConfig) {
	*out = *in
	if in.Streams != nil {
		in, out := &in.Streams, &out.Streams
		*out = make([]StreamSchema, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SinkMapping != nil {
		in, out := &in.SinkMapping, &out.SinkMapping
		*out = make([]SinkMappingConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapperConfig.
func (in *MapperConfig) DeepCopy() *MapperConfig {
	if in == nil {
		return nil
	}
	out := new(MapperConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pipeline) DeepCopyInto(out *Pipeline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pipeline.
func (in *Pipeline) DeepCopy() *Pipeline {
	if in == nil {
		return nil
	}
	out := new(Pipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Pipeline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineList) DeepCopyInto(out *PipelineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Pipeline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineList.
func (in *PipelineList) DeepCopy() *PipelineList {
	if in == nil {
		return nil
	}
	out := new(PipelineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineSpec) DeepCopyInto(out *PipelineSpec) {
	*out = *in
	in.Mapper.DeepCopyInto(&out.Mapper)
	in.Ingestor.DeepCopyInto(&out.Ingestor)
	in.Join.DeepCopyInto(&out.Join)
	out.Sink = in.Sink
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineSpec.
func (in *PipelineSpec) DeepCopy() *PipelineSpec {
	if in == nil {
		return nil
	}
	out := new(PipelineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineStatus) DeepCopyInto(out *PipelineStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineStatus.
func (in *PipelineStatus) DeepCopy() *PipelineStatus {
	if in == nil {
		return nil
	}
	out := new(PipelineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SinkMappingConfig) DeepCopyInto(out *SinkMappingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SinkMappingConfig.
func (in *SinkMappingConfig) DeepCopy() *SinkMappingConfig {
	if in == nil {
		return nil
	}
	out := new(SinkMappingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SinkOperatorConfig) DeepCopyInto(out *SinkOperatorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SinkOperatorConfig.
func (in *SinkOperatorConfig) DeepCopy() *SinkOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(SinkOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamDataField) DeepCopyInto(out *StreamDataField) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamDataField.
func (in *StreamDataField) DeepCopy() *StreamDataField {
	if in == nil {
		return nil
	}
	out := new(StreamDataField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamSchema) DeepCopyInto(out *StreamSchema) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamSchema.
func (in *StreamSchema) DeepCopy() *StreamSchema {
	if in == nil {
		return nil
	}
	out := new(StreamSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamSchemaConfig) DeepCopyInto(out *StreamSchemaConfig) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]StreamDataField, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamSchemaConfig.
func (in *StreamSchemaConfig) DeepCopy() *StreamSchemaConfig {
	if in == nil {
		return nil
	}
	out := new(StreamSchemaConfig)
	in.DeepCopyInto(out)
	return out
}
