name: Chart Version Bump

on:
  workflow_call:

jobs:
  bump-app-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "✅ Version extracted from tag: $VERSION"
          else
            echo "❌ This workflow should only run on tag pushes"
            exit 1
          fi
      
      - name: Extract chart version
        id: chart_version
        run: |
          CHART_VERSION=$(cat charts/glassflow-operator/Chart.yaml | grep "version:" | awk '{print $2}')
          echo "chart_version=$CHART_VERSION" >> $GITHUB_OUTPUT
          echo "✅ Chart version extracted from Chart.yaml: $CHART_VERSION"

      - name: Update chart version in Chart.yaml
        run: |
          # Split version into parts
          IFS='.' read -r major minor patch <<< "$CHART_VERSION"

          # Bump patch version
          patch=$((patch + 1))
          NEW_VERSION="${major}.${minor}.${patch}"

          echo "Updating chart version in Chart.yaml to $NEW_VERSION"
          sed -i "s/^version: .*/version: $NEW_VERSION/" charts/glassflow-operator/Chart.yaml
          cat charts/glassflow-operator/Chart.yaml

      - name: Update operator version in Chart.yaml
        run: |
          echo "Updating operator version in Chart.yaml to ${{ steps.version.outputs.version }}"
          sed -i "s/^appVersion: .*/appVersion: ${{ steps.version.outputs.version }}/" charts/glassflow-operator/Chart.yaml
          cat charts/glassflow-operator/Chart.yaml

      - name: Commit and push version changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
          message: "chore: bump chart app version to ${{ steps.version.outputs.version }}" 